### ISSUE TITLE
Momentum corrections to velocities are output wrongly

### ISSUE THREAD

**Issue by qwenger** [CullanHowlett/l-picola#1]
I do not know whether the momentum corrections do make a difference or not, but the line https://github.com/CullanHowlett/l-picola/blob/master/src/main.c#L810 is obviously wrong: sumx is used for all three dimensions, where sumx/sumy/sumz should be used instead.

**Comment by cullanhowlett** [comment]
Hi! Thanks very much for pointing this out :) This and another issue with the GADGET style output (npartTotHighWord was calculated incorrectly, leading to incorrect numbers of particles in the header for large simulations) have now been fixed. For my test case (which is the example run in files/) sumx, sumy and sumz are zero to floating point precision, so it should have negligible effect for most cases.

**Comment by HAWinther** [comment]
Hi Cullan. This reminded me of a similar thing (which should also have negligible effects). In 2LPT.c Line 1407 and 1408 the += sumdis should be -= sumdis right?

**Comment by cullanhowlett** [comment]
Hmm, yes the way these are written it should be a minus sign, but for the typical way the code is run this is negligible. However, I added this in without really thinking and I'm now not convinced that we expect the individual displacements to average to zero (rather we expect the Lagrangian potentials to average to zero, or the net velocity of each particle due to the combined ZA and 2LPT displacements). In that case I should remove this part and add something similar around line 208 in main.c when the particle velocities are created.

**Comment by cullanhowlett** [comment]
Sign and name for the momentum corrections have been corrected. In all the cases I tested the corrections were negligible anyway. Closing this issue.
