### ISSUE TITLE
GSL roundof error

### ISSUE THREAD

**Issue by oliveirara** [CullanHowlett/l-picola#3]
Hi @CullanHowlett,

I ran L-Picola was able to compile and run L-Picola for some simulations following all the procedures from the documentation. However, for the parameters bellow I found this problem:

> gsl: qag.c:248: ERROR: roundoff error prevents tolerance from being achieved

I used these parameters for configuration file (LH0004.txt):

> NumFilesWrittenInParallel 1
> UseCOLA 1
> Buffer 2
> Nmesh 512
> Nsample 512
> Box 1000000.0
> Init_Redshift 9
> SphereMode 0
> WhichSpectrum 1
> WhichTransfer 0
> StepDist 0
> DeltaA 0
> nLPT -2.5
> UnitLength_in_cm                3.085678e21
> UnitMass_in_g                   1.989e43
> UnitVelocity_in_cm_per_s        1e5
> InputSpectrum_UnitLength_in_cm  3.085678e24
> OutputRedshiftFile output_redshifts.txt
> Omega 0.1433 
> OmegaBaryon 0.06347 
> OmegaLambda 0.8567 
> HubbleParam 0.6127 
> Sigma8 0.7699 
> PrimordialIndex 1.1501 
> FileBase LH0004 
> OutputDir LH0004 
> Seed 4 
> FileWithInputSpectrum Pk_mm_z=0.000.txt 
> FileWithInputTransfer Pk_mm_z=0.000.txt

with `Pk_mm_z=0.000.txt` and `output_redshifts.txt` attached.

[LH0004.txt](https://github.com/CullanHowlett/l-picola/files/5435811/LH0004.txt)
[Pk_mm_z=0.000.txt](https://github.com/CullanHowlett/l-picola/files/5435804/Pk_mm_z.0.000.txt)
[output_redshifts.txt](https://github.com/CullanHowlett/l-picola/files/5435808/output_redshifts.txt)

I tested on two computers (on a cluster and on my laptop). The logs are here:
[slurm-5492306.txt](https://github.com/CullanHowlett/l-picola/files/5435814/slurm-5492306.txt)
[log.txt](https://github.com/CullanHowlett/l-picola/files/5435819/log.txt)

Also, I compiled L-PICOLA with these flags (and changed some paths properly):

`MEMORY_MODE`
`PARTICLE_ID`
`GADGET_STYLE`
`TIMING`

and I disabled `ONLY_ZA` because I wanted 2LPT.

Let me know if you need more information about this. Thank you!

**Comment by oliveirara** [comment]
Changing `GSL_INTEG_GAUSS41` to `6` (or `GSL_INTEG_GAUSS61`) from src/power.c (line 511) solves this issue. Also, all other gsl integrals were defined with 61 points for Gauss-Kronrod rules.

**Comment by oliveirara** [comment]
I am re-opening this issue because this problem still exists, but for another type of cosmology with these parameters:

  Omega Matter(z=0) = 0.108300
  Omega Lambda(z=0) = 0.891700
  Omega Baryon(z=0) = 0.044470
  Hubble Parameter(z=0) = 0.862900
  Sigma8(z=0) = 0.900300
  Primordial Index = 1.140700

**Comment by HAWinther** [comment]
> I am re-opening this issue because this problem still exists, but for another type of cosmology with these parameters:
> 
> Omega Matter(z=0) = 0.108300
> Omega Lambda(z=0) = 0.891700
> Omega Baryon(z=0) = 0.044470
> Hubble Parameter(z=0) = 0.862900
> Sigma8(z=0) = 0.900300
> Primordial Index = 1.140700

Just from a quick glance at this the issue might be due to your power-spectrum having much stronger oscillations (due to the high value of OmegaB/OmegaM ~1/2) than a typical input to the code (which would be a model with OmegaB/OmegaM ~ 1/6 which will have a fairly smooth power-spectrum and it will stay fairly smooth even after multiplication with the tophat window in the sigma8 integration - but yours will not). Standard quadratures are generally not great for rapid oscillations. To solve this the simplest thing to try is to just reduce the tolerance in the integration in the code (1e-6, 1e-4) down to, for example, (1e-6, 1e-3) or even 1e-2 - you probably don’t need to guarantee tons of digits of accuracy in the sigma8 normalization. Another solution is to try Romberg integration in conjunction with changing the integral to be done over log(k) instead of k (helps to “stretch” out the oscillations as right now the integration is over a huge interval [0,~60] and most of the weight comes from rapid oscillations located in [0, ~0.5-1]).

**Comment by cullanhowlett** [comment]
Hi @oliveirara, thanks for bringing this to my attention. Hans is exactly right, this is because the code had difficulty integrating the power spectrum for the cosmologies you provided when trying to compute Sigma_8. 

I have pushed an update that now uses `GSL_CQUAD` rather than `GSL_QAG` as this is much more stable in my experience (at the cost of speed, which is perfectly fine as Sigma_8 only needs computing once). It now seems to work for the case above, but let me know if you have any more trouble.

**Comment by oliveirara** [comment]
Hi @HAWinther and @CullanHowlett, thank you all for explaining what's going on in this case. Also, this error appeared for other simulations sampled with Om, Ob, h, ns, and s8 sampled in the range {[0.1, 0.5], [0.03, 0.07], [0.5, 0.9], [0.8, 1.2], [0.6, 1.0]}. I re-run some simulations that this error appeared with this new commit, and I can confirm that this issue is solved.
